"use strict";(self.webpackChunkcra_template_doly_site=self.webpackChunkcra_template_doly_site||[]).push([[22],{47355:function(o,n,t){t.r(n);var d=t(22980),u=t(45926),c=t(84833),m=t(58300),p=t(44390),a=t(43362),v=t(81296),x=t(76366),l=t(33217),r=t(78165),s=t(75271),_=t(79631),e=t(52676);function i(){return(0,e.jsx)(l.dY,{children:(0,e.jsx)(s.Suspense,{fallback:(0,e.jsx)(r.Z,{}),children:(0,e.jsx)(e.Fragment,{children:(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("h1",{id:"environment-variable",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#environment-variable",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Environment variable"]}),(0,e.jsxs)("p",{children:[_.texts[0].value,(0,e.jsx)("code",{children:_.texts[1].value}),_.texts[2].value,(0,e.jsx)("a",{href:"https://github.com/toddbluhm/env-cmd",children:_.texts[3].value}),_.texts[4].value]}),(0,e.jsx)("p",{children:_.texts[5].value}),(0,e.jsx)(a.Z,{lang:"text",children:_.texts[6].value}),(0,e.jsxs)("p",{children:[_.texts[7].value,(0,e.jsx)("a",{href:"https://create-react-app.dev/docs/advanced-configuration/",children:_.texts[8].value}),_.texts[9].value,(0,e.jsx)("code",{children:_.texts[10].value}),_.texts[11].value]}),(0,e.jsxs)("p",{children:[_.texts[12].value,(0,e.jsx)("code",{children:_.texts[13].value}),_.texts[14].value]}),(0,e.jsx)(a.Z,{lang:"typescript",children:_.texts[15].value}),(0,e.jsxs)("h2",{id:"differentiate-the-interface-address-of-different-environments",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#differentiate-the-interface-address-of-different-environments",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Differentiate the interface address of different environments"]}),(0,e.jsxs)("p",{children:[(0,e.jsx)("code",{children:_.texts[16].value}),_.texts[17].value]}),(0,e.jsx)(a.Z,{lang:"text",children:_.texts[18].value}),(0,e.jsxs)("p",{children:[_.texts[19].value,(0,e.jsx)("code",{children:_.texts[20].value}),_.texts[21].value,(0,e.jsx)("code",{children:_.texts[22].value}),_.texts[23].value]}),(0,e.jsxs)("h2",{id:"development-environment-printing-information",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#development-environment-printing-information",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Development environment printing information"]}),(0,e.jsx)("p",{children:_.texts[24].value}),(0,e.jsx)(a.Z,{lang:"typescript",children:_.texts[25].value})]})})})})}n.default=i},79631:function(o,n,t){t.r(n),t.d(n,{texts:function(){return d}});const d=[{value:"In ",paraId:0,tocIndex:0},{value:"config/env.js",paraId:0,tocIndex:0},{value:" the configuration variables and various operating environments, use of ",paraId:0,tocIndex:0},{value:"env-cmd",paraId:0,tocIndex:0},{value:" arrangement.",paraId:0,tocIndex:0},{value:"The following are the commonly used environment variables:",paraId:1,tocIndex:0},{value:`PUBLIC_URL         # Static resource base path
REACT_APP_ENV      # Application operating environment dev test prod
REACT_APP_API      # Interface basic path
`,paraId:2,tocIndex:0},{value:"For more built-in environment variables, please refer to ",paraId:3,tocIndex:0},{value:"Advanced Configuration",paraId:3,tocIndex:0},{value:" . If you need a custom environment variables, use the ",paraId:3,tocIndex:0},{value:"REACT_APP_*",paraId:3,tocIndex:0},{value:" name.",paraId:3,tocIndex:0},{value:"Project by ",paraId:4,tocIndex:0},{value:"process.env.*",paraId:4,tocIndex:0},{value:" accessing:",paraId:4,tocIndex:0},{value:`console.log(process.env.REACT_APP_ENV);
`,paraId:5,tocIndex:0},{value:"src/utils/request.ts",paraId:6,tocIndex:1},{value:" You can see the following code in:",paraId:6,tocIndex:1},{value:`baseURL: process.env.REACT_APP_API
`,paraId:7,tocIndex:1},{value:"In the development environment, the interface used may be a local mock ",paraId:8,tocIndex:1},{value:'""',paraId:8,tocIndex:1},{value:", and in the production build it is ",paraId:8,tocIndex:1},{value:"http://prod.api.example.com/",paraId:8,tocIndex:1},{value:" .",paraId:8,tocIndex:1},{value:"Only print information to the console in the development environment.",paraId:9,tocIndex:2},{value:`if (process.env.REACT_APP_ENV === 'dev') {
  // console.log(something);
}
`,paraId:10,tocIndex:2}]}}]);
